### ISSUE TITLE
Umbrella: Windows support

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/rustic_core#19]
This is the tracking issue to collect the needed steps in order to support windows as OS:

- [x] make rustic compile on windows rustic-rs/rustic#11 
- [ ] treat non-unicode filenames and quoting of filenames (+link targets?) correctly
- [ ] treat file permissions correctly
- [ ] treat user/group correctly
- [ ] treat special files (device,...) correctly
- [x] handle paths (like C:\...) in snapshots rustic-rs/rustic#510 and rustic-rs/rustic#542
- [x] handle repo path containing a drive (like `-r C:\path\to\repo`) rustic-rs/rustic#495
- [ ] handle links correctly
- [ ] document windows behavior
- [x] Correctly use a parent snapshot rustic-rs/rustic#542
- [ ] Add [VSS](https://learn.microsoft.com/en-us/windows-server/storage/file-server/volume-shadow-copy-service) support ([how others do it](https://www.nakivo.com/blog/what-is-volume-shadow-copy-service/))
- [ ] restore issues (e.g. rustic-rs/rustic#635)
