### ISSUE TITLE
Reworking includes/excludes

### ISSUE THREAD

**Issue by simonsan** [rustic-rs/rustic_core#327]
## Open questions
- [ ] What are the pain points we are trying to fix?
- [ ] when we decide to add backup possibilities from other sources (opendal, rclone,..), we also need options to include/exclude which should be general and not depending on the specific backend. Currently, the includes/excludes are handled by the `ignore` crate which only works for local FS

## Features to add

- [ ] add something like `exclude-fn` using `rhai`

## TODO
- [ ] implement testing first for the current way that includes and excludes work
- [ ] adjust the tests in the same PR that we implement the new way how includes and excludes should work
